name: ig_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.0
  firebase_core: ^2.13.0
  firebase_picture_uploader: ^1.3.2
  firebase_storage: ^11.2.0
  image_picker: ^0.8.7+5
  


  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  provider: ^6.0.5
  file_picker: ^5.3.0
  carousel_slider: ^4.2.1
  firebase_database: ^10.2.1
  firebase_core_dart: ^1.0.1
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/