// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhJfahoahfRNK2Dv4K-lVvx2jtz3vATOk',
    appId: '1:174566426839:web:991689ce035230551b4892',
    messagingSenderId: '174566426839',
    projectId: 'instagramproject-e6ec7',
    authDomain: 'instagramproject-e6ec7.firebaseapp.com',
    storageBucket: 'instagramproject-e6ec7.appspot.com',
    measurementId: 'G-4STB6NGT3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyIjQBqCMRYCO1VLGX3SqxeQd6jJ_kBds',
    appId: '1:174566426839:android:88b87e4e78d855951b4892',
    messagingSenderId: '174566426839',
    projectId: 'instagramproject-e6ec7',
    storageBucket: 'instagramproject-e6ec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWgFMl0jF4Bcjg-rtEMLsXhAWldUxn9Uc',
    appId: '1:174566426839:ios:b14e8d390af658a81b4892',
    messagingSenderId: '174566426839',
    projectId: 'instagramproject-e6ec7',
    storageBucket: 'instagramproject-e6ec7.appspot.com',
    iosClientId: '174566426839-qq4nkt2h9l6fen8cbikt0vuufl14ak68.apps.googleusercontent.com',
    iosBundleId: 'com.example.igClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWgFMl0jF4Bcjg-rtEMLsXhAWldUxn9Uc',
    appId: '1:174566426839:ios:b14e8d390af658a81b4892',
    messagingSenderId: '174566426839',
    projectId: 'instagramproject-e6ec7',
    storageBucket: 'instagramproject-e6ec7.appspot.com',
    iosClientId: '174566426839-qq4nkt2h9l6fen8cbikt0vuufl14ak68.apps.googleusercontent.com',
    iosBundleId: 'com.example.igClone',
  );
}
