// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvKY5sVf_ByQiGUU2KL0-ruaFtPDcahE',
    appId: '1:199311410005:web:242742595f2cf5250665dc',
    messagingSenderId: '199311410005',
    projectId: 'instagram-clone-b6009',
    authDomain: 'instagram-clone-b6009.firebaseapp.com',
    storageBucket: 'instagram-clone-b6009.appspot.com',
    measurementId: 'G-B8T2HECF4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVvWbm6k-qITjBgbya9IRUVGr0ltrMcLU',
    appId: '1:199311410005:android:3ede734d0843cf690665dc',
    messagingSenderId: '199311410005',
    projectId: 'instagram-clone-b6009',
    storageBucket: 'instagram-clone-b6009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC9Fbp_prEM3Oypp00XGFFY_tAihr-QOw',
    appId: '1:199311410005:ios:a3e646ada836a60f0665dc',
    messagingSenderId: '199311410005',
    projectId: 'instagram-clone-b6009',
    storageBucket: 'instagram-clone-b6009.appspot.com',
    iosClientId: '199311410005-d9oa9ecscbp7hiifkaeds4kg2h4ov39c.apps.googleusercontent.com',
    iosBundleId: 'com.example.igClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC9Fbp_prEM3Oypp00XGFFY_tAihr-QOw',
    appId: '1:199311410005:ios:a3e646ada836a60f0665dc',
    messagingSenderId: '199311410005',
    projectId: 'instagram-clone-b6009',
    storageBucket: 'instagram-clone-b6009.appspot.com',
    iosClientId: '199311410005-d9oa9ecscbp7hiifkaeds4kg2h4ov39c.apps.googleusercontent.com',
    iosBundleId: 'com.example.igClone',
  );
}
